server:
  port: 8070
grpc:
  server:
    port: 9070
spring:
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: scd_tx_group
  # DataSource
  datasource:
    account:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/account
      username: sunshengteng
      password: 208521
      maximumPoolSize: 20
      minimumIdle: 3
    member:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/member
      username: sunshengteng
      password: 208521
      maximumPoolSize: 20
      minimumIdle: 3
    item:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/item
      username: sunshengteng
      password: 208521
      maximumPoolSize: 20
      minimumIdle: 3
  # JPA
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        use_sql_comments: true
        type: trace
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  #  config-location: classpath:mybatis-config.xml
  type-aliases-package: cn.sst.scd.**.entity
# Logger
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework: error


# Http服务配置
http:
  #ERP 服务
  erp:
    # 获取物料的可要货数量
    canRequiredNum:
      host: http://crm.dahua-crm-dahua-crm.testms.com
      uri: /dahua-erp-base/Orders/prjUnship
      method: GET
    # 获取物料的已发货总量、已取消总量
    shipAndCancelQty:
      host: http://crm.dahua-crm-dahua-crm.testms.com
      uri: /dahua-erp-base/Orders/prjShip
      method: GET