package cn.sst.scd.dao;

import cn.sst.scd.entity.BatchInfo;
import cn.sst.scd.entity.BatchInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BatchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    long countByExample(BatchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    int insert(BatchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    int insertSelective(BatchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    List<BatchInfo> selectByExample(BatchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    BatchInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BatchInfo record, @Param("example") BatchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BatchInfo record, @Param("example") BatchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BatchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BatchInfo record);
}