server:
  port: 8070

spring:
  # DataSource
  datasource:
    account:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/account
      username: sunshengteng
      password: 208521
    member:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/member
      username: sunshengteng
      password: 208521
  # JPA
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        use_sql_comments: true
        type: trace
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect


# Logger
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework: error


