server:
  port: 8070

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/member_dev?useSSL=false
    username: sunshengteng
    password: 208521
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        use_sql_comments: true
        type=trace:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework: error