server:
  port: 8070
grpc:
  server:
    port: 9070
spring:
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: scd_tx_group
  # DataSource
  datasource:
    account:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/account
      username: sunshengteng
      password: 208521
    member:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/member
      username: sunshengteng
      password: 208521
    item:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/item
      username: sunshengteng
      password: 208521
  # JPA
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        use_sql_comments: true
        type: trace
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect


# Logger
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework: error


