server:
  port: 8070


spring:
  application:
    name: item-service
  # Mybatis
  datasource:
    account:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/account
      username: sunshengteng
      password: 208521
    member:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/member
      username: sunshengteng
      password: 208521
  # JPA
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        use_sql_comments: true
        type: trace
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

#Eureka实例名，集群中根据这里相互识别
eureka:
  instance:
    hostname: item-service
    prefer-ip-address: true
  ##续约时间
  #    lease-expiration-duration-in-seconds: 90
  ##定时任务是时间，每个隔多少秒去重新刷新续约时间
  #    lease-renewal-interval-in-seconds: 30
  #客户端
  client:
    register-with-eureka: true
    fetch-registry: true
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
# Logger
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework: error


