server:
  port: 8081


spring:
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: scd_tx_group
  # AOP配置
  aop:
    proxy-target-class: true
  # JSON 缩进输出
  jackson:
    serialization:
      indent_output: true

account:
  number:


logging:
  level:
    # security 日志
    org.springframework.security: info

# Http服务配置
http:
  #ERP 服务
  erp-server:
    host: http://crm.dahua-crm-dahua-crm.testms.com
    name: erp-server
  #CRM 服务
  crm-server:
    host: http://10.1.1.5:8080
    name: crm-server


